version: "3.9"
services:
    redis:
        restart: unless-stopped
        image: redis
        ports:
            - "6379:6379"
        environment:
            ALLOW_EMPTY_PASSWORD: "yes"
        networks:
            - app-network
    php-fpm:
        container_name: php-fpm
        build: 
            context: ./php-fpm
        volumes:
            - ~/code:/var/www
        networks:
            - app-network
        restart: unless-stopped
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        volumes:
            - ~/code:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
        depends_on:
            - php-fpm
networks:
    app-network:
        driver: bridge
